plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs

nodeLinker: pnp

packageExtensions:
  "eslint-config-next@*":
    dependencies:
      "next": "*"
      "react": "*"
      "@types/react":  "*"
      "@types/react-dom":  "*"
      "@types/react-is":  "*"
      "react-dom": "*"
  